//
// Created by dor on 27/07/2020.
//

#ifndef DATASTRUCTURES_ALGORITHMS_COMMON_HPP
#define DATASTRUCTURES_ALGORITHMS_COMMON_HPP

#define EXPECT_SUCCESS(expr) EXPECT_EQ(RETURNCODE_SUCCESS, (expr))

#endif //DATASTRUCTURES_ALGORITHMS_COMMON_HPP
